{% set name = "hatch-fancy-pypi-readme" %}
{% set version = "24.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_fancy_pypi_readme-{{ version }}.tar.gz
  sha256: 44dd239f1a779b9dcf8ebc9401a611fd7f7e3e14578dcf22c265dfaf7c1514b8

build:
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - hatch-fancy-pypi-readme=hatch_fancy_pypi_readme.__main__:main

requirements:
  host:
    - hatchling
    - pip
    - python
  run:
    - hatchling
    - python
    - tomli  # [py<311]
    - typing-extensions  # [py<38]

test:
  source_files:
    - AUTHORS.md
    - CHANGELOG.md
    - LICENSE.txt
    - pyproject.toml
    - README.md
    - src
    - tests
  imports:
    - hatch_fancy_pypi_readme
  commands:
    - pip check
    - hatch-fancy-pypi-readme --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - build
    - pip
    - pytest

about:
  home: https://github.com/hynek/hatch-fancy-pypi-readme
  summary: Fancy PyPI READMEs with Hatch
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
